<?php
include("function/add_product.php");
include("function/admin_function.php");
include("function/cat_brand_list.php");
include("function/db.php");
include("function/edit_function.php");
include("function/order_dash_function.php");
include("function/overview_function.php");
include("function/product_list.php");
include("function/user_function.php");
 ?>
